// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olhctfcihsuaplcmuyvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saGN0ZmNpaHN1YXBsY211eXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzE3ODgsImV4cCI6MjA2NjUwNzc4OH0.tXCxdH1C65X6xCNk094nA2DB1Z_7C7Ugld_Dw8UrTRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);